### ISSUE TITLE
fast_jsonapi here

### ISSUE THREAD

**Issue by sckott** [sckott/rjsonapi#10]
following on https://github.com/Netflix/fast_jsonapi 

been playing with possibility of implementing something similar here (or possibly break off into new pkg)

**Comment by sckott** [comment]
@trestletech after seeing https://github.com/Netflix/fast_jsonapi for Ruby, I wanted to explore that for R - started playing https://github.com/ropensci/rjsonapi/blob/master/R/JsonAPIModel.R - but I'd imagine the place users would use this might be in `plumber` - so just curious if you think this is of interest at all? That is, do you see users wanting to use JSONAPI. If yes, could something like `fast_jsonapi` for R be worth doing?

**Comment by trestletech** [comment]
Interesting! I had a request for GraphQL recently which might fall in this same vein of "do smarter things given a more comprehensive knowledge of all the things I might try to render".

I'm not familiar with the JSONAPI spec so I'd need to spend a little more time getting familiar. We'd probably need to decide whether plumber is going to be pluggable in supporting a variety of different specs (currently Swagger, perhaps someday GraphQL and/or JSONAPI) or if we want to pick one and roll with it. I'm not sure on the answer right now.

If this is something you're excited about or see a lot of benefits to, I'd love to chat with you about it or learn more. I'm not sure I'm fully groking the ecosystem. Feel free to email me to set something up if you're interested.

**Comment by sckott** [comment]
Thanks for your quick reply. Neat about being able to possibly do GraphQL in the future. I'll think more about how it would work, and get back to you
