### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by ghost** [sckott/rjsonapi#7]
Great package, looks like version 1 is hardcoded.

```
> (conn <- jsonapi_connect("http://localhost:8000/v0"))
<jsonapi_connection>
  Public:
    base_url: function () 
    cli: HttpClient, R6
    content_type: application/vnd.api+json
    headers: NULL
    initialize: function (url, version, content_type, headers = list(), ...) 
    opts: list
    route: function (endpt, query = NULL, include = NULL, error_handler = private$check, 
    routes: function (...) 
    status: function (...) 
    url: http://localhost:8000/v0
    version: v1
  Private:
    check: function (x, ...) 
    fromjson: function (...) 
> conn$version
[1] "v1"
```

**Comment by ghost** [comment]
appology missed `initialize: function (url, version, content_type, headers = list(), ...) `

**Comment by sckott** [comment]
thanks for the issue @ola-t 

so the default value is `v1` see https://github.com/ropensci/rjsonapi/blob/master/R/connect.R#L92

The way the function is setup to work is that you pass in the base url like `http://localhost:8000` as first param, then version as second param like `v0` or `v1`

**Comment by ghost** [comment]
Yes, I realized that. Might be worth updating readme ;-)

**Comment by sckott** [comment]
done
