### ISSUE TITLE
Add a vignette

### ISSUE THREAD

**Issue by sckott** [sckott/rjsonapi#8]
This package needs more documentation!  Help out the community by contributing a vignette. If you don't know what a vignette is, check out http://r-pkgs.had.co.nz/vignettes.html for an introduction.  

If you aren't sure how to contribute on github checkout https://github.com/ropensci/rjsonapi/blob/master/.github/CONTRIBUTING.md 

Keep in mind our code of conduct https://github.com/ropensci/rjsonapi/blob/master/CONDUCT.md

**Comment by brooklynbagel** [comment]
I'll try to take a look at the package and see if I can write something useful.

**Comment by sckott** [comment]
thanks @brooklynbagel

**Comment by brooklynbagel** [comment]
@sckott so what kind of vignette are you looking for? You already have the README. However I could see giving some more explanation for how `conn$route` works. Its arguments can be found in the documentation for `jsonapi_connect` but that might be a little confusing so putting it in a vignette might be helpful.

**Comment by sckott** [comment]
well, it's okay if there's duplicated content in the vignette and readme since some people may only look at the readme and some only look at the vignette, different audiences but some overlap probably. 

So duplicating README more or less is good plus whatever else you think is useful. more on `conn$route` sounds good e.g.,
